name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - if: ${{ startsWith(matrix.os, 'macos') }}
      run: brew install helib
    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        make
        sudo make install
    - name: Test
      run: |
        morph-cli keygen
        morph-server &
        sleep 1
        ./run_tests.sh
