name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install libntl-dev
          git clone --branch v2.3.0 https://github.com/homenc/HElib.git
          cd HElib
          mkdir build && cd build
          cmake ..
          make
          sudo make install
          sudo ldconfig
      - if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install helib
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make
          sudo make install
      - name: Test
        run: |
          morph-cli keygen
          morph-server &
          sleep 1
          ./run_tests.sh
          g++ -std=c++17 examples/hello.cpp -lmorph -lpthread -lhelib -lntl -o hello
          ./hello
